#!/bin/bash

if [[ $# -eq 3 ]]; then
	# post-checkout
	PREV_REF=$1
	CURR_REF=$2
	if [[ $3 == 1 ]]; then
		FLAG_TYPE="branch"
	else
		FLAG_TYPE="file"
	fi
elif [[ $# -eq 0 ]]; then
	# post merge
	PREV_REF='HEAD@{1}'
	CURR_REF="HEAD"
	FLAG_TYPE="branch"
else
	echo "Unknown hook: $(basename $0)"
	exit 1
fi

# list changed files
FILES=$(git diff --name-only "$PREV_REF" "$CURR_REF")

# don't bother when just checking out a file
if [[ $FLAG_TYPE == "branch" ]]; then
	# force windows style symlinks when possible
	if type symlink-reflow &> /dev/null && ! grep 'winsymlinks:native' <<< $CYGWIN &> /dev/null; then
		symlink-reflow -f .
	fi

	# update npm dependencies only if package.json has changed
	if ( type npm && echo "$FILES" | grep ^package.json ) &> /dev/null; then
		>&2 echo -e "\e[34m----- package.json changed updating npm -----\e[0m"
		npm install --loglevel=error
		npm prune
	fi

	# update bower dependencies only if bower.json has changed
	if ( echo "$FILES" | grep ^bower.json ) &> /dev/null; then
		if type ./node_modules/.bin/bower &> /dev/null; then
			BOWER_BIN=./node_modules/.bin/bower
		elif type bower &> /dev/null; then
			BOWER_BIN=bower
		fi

		if [[ -n $BOWER_BIN ]]; then
			>&2 echo -e "\e[34m----- bower.json changed updating bower -----\e[0m"
			$BOWER_BIN install --loglevel=error
			$BOWER_BIN prune
		fi
	fi
fi
