#!/bin/bash

# force windows style symlinks when possible
if type symlink-reflow &> /dev/null && ! grep 'winsymlinks:native' <<< $CYGWIN &> /dev/null; then
	symlink-reflow -f .
fi

rm -f tmp/class_list.json
rm -f tmp/static/*

node_modules/.bin/bower update || true

# sync to remote server if necessary
bash .build/sync-files
