#!/bin/bash

# force windows style symlinks when possible
if type symlink-reflow &> /dev/null && ! grep 'winsymlinks:native' <<< $CYGWIN &> /dev/null; then
	symlink-reflow -f .
fi

rm -f tmp/class_list.json
rm -f tmp/static/*

if [[ "$1" != "$2" ]]; then
	# update npm dependencies
	if type npm &> /dev/null; then
		npm install --quiet &
	fi

	# update npm dependencies
	if type bower &> /dev/null; then
		bower install --quiet &
	fi
fi
