#!/bin/bash

# sync to remote server if necessary
REMOTE_SERVER=$(git config --get code.remote-host)
REMOTE_PATH=$(git config --get code.remote-path)
if [[ -n $REMOTE_SERVER ]] && [[ -n $REMOTE_PATH ]]; then

rsync -av --delete --delete-excluded --links -K \
	-e 'ssh -o ConnectTimeout=1' \
	--chmod a+rwx,g+rx,o+rx,g-w,o-w \
	--exclude '.git' \
	--exclude '.DS_Store' \
	--exclude '.buildpath' \
	--exclude '.project' \
	--exclude '.settings' \
	--exclude '.cache' \
	. \
	$REMOTE_SERVER:$REMOTE_PATH/

ssh $REMOTE_SERVER "chmod 777 -R $REMOTE_PATH/tmp"

fi
